project:
  type: website

website:
  title: "HumanFRST Lab"
  navbar:
    left:
      - pages/team/index.qmd
      - pages/research/index.qmd
      - pages/publications/index.qmd
      - pages/posts/index.qmd
      - pages/contact.qmd
      - pages/opportunities.qmd
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: solar
      # light: journal
      # dark: [solar, dark-style.css] # united # simplex # journal
    css: [css/styles.css, css/dark-styles.css]



