project:
  type: website
  output-dir: docs

website:
  site-path: /HumanFRSTLab/
  title: "HumanFRST Group"
  navbar:
    left:
      - pages/team/index.qmd
      - text: "Research"
        href: pages/research/index.qmd
      - text: "Publications"
        href: pages/publications/index.qmd
      - text: "Contact"
        href: pages/contact.qmd
      - text: "Opportunities"
        href: pages/opportunities.qmd
    # right:
      # - icon: github
      #   href: https://github.com/
      #   - icon: twitter
      #     href: https://twitter.com
  page-footer:
    center:
      - text: "<span><span>Proudly supported by</span></span>"
      - text: "![](/assets/misc/iitr_logo.png){fig-alt='IIT Roorkee' height=50px}<br>IIT Roorkee"
        href: https://iitr.ac.in/
      # - text: "![](/assets/misc/serb_logo.png){fig-alt='SERB' height=50px}<br>SERB"
      #   href: https://serb.gov.in/
    # center:
    #   - text: "About"
    #     href: pages/contact.qmd
    # right:
    #   - icon: twitter
    #     href: https://twitter.com/quarto_pub
    #     aria-label: Quarto Twitter
    #   - icon: github
    #     href: https://github.com/quarto-dev/quarto-cli
    #     aria-label: Quarto GitHub
    #   - icon: rss
    #     href: https://quarto.org/docs/blog/index.xml
    #     aria-label: Quarto Blog RSS
format:
  html:
    theme:
      light: [cosmo, css/light-styles.scss]
      dark: [solar, css/dark-styles.scss] # united # simplex # journal

    css: [css/styles.css]
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Rokkitt&display=swap" rel="stylesheet">

    mainfont: Rokkitt
    fontsize: 1.1em


